const fs = require('fs')
const path = require('path')
const { readFromFile } = require('./contractAddress')

const BASE_SEPOLIA_CHAIN_ID = 84532
const featureName = process.env.FEATURE_NAME
const startBlock = process.env.BASE_SEPOLIA_SUBGRAPH_START_BLOCK || '41100000'

const indexerRoot = path.resolve(__dirname, '..', '..', '..', 'RentalityPrototypeNEW', 'indexer', 'gateway')
const subgraphPath = path.join(indexerRoot, 'subgraph.yaml')
const generatedAddressesPath = path.join(indexerRoot, 'src', 'handlers', 'generatedLocalhostAddresses.ts')

function readAddress(contractName) {
  const address = readFromFile(contractName, BASE_SEPOLIA_CHAIN_ID)
  if (!address) {
    throw new Error(`No ${contractName} address found for Base Sepolia`)
  }
  return address
}

function writeSubgraphYaml(notificationServiceAddress) {
  const content = `specVersion: 1.3.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: RentalityNotificationService
    network: base-sepolia
    source:
      address: "${notificationServiceAddress}"
      abi: RentalityNotificationService
      startBlock: ${startBlock}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - RentalityEvent
      abis:
        - name: RentalityNotificationService
          file: ./abis/RentalityNotificationService.json
        - name: CarGatewayRead
          file: ./abis/CarGatewayRead.json
        - name: RentalityTripService
          file: ./abis/RentalityTripService.json
        - name: RentalityUserService
          file: ./abis/RentalityUserService.json
      eventHandlers:
        - event: RentalityEvent(indexed uint8,uint256,uint8,indexed address,indexed address,uint256)
          handler: handleRentalityEvent
      file: ./src/rentality-gateway.ts
`

  fs.writeFileSync(subgraphPath, content)
  console.log(`Updated Base Sepolia subgraph manifest: ${subgraphPath}`)
}

function writeGeneratedAddresses(addresses) {
  const content = `// Auto-generated by RentalitySmartContracts/scripts/utils/syncBaseSepoliaIndexerConfig.js
export const CAR_GATEWAY_READ_ADDRESS = "${addresses.carGatewayRead}"
export const RENTALITY_TRIP_SERVICE_ADDRESS = "${addresses.tripQuery}"
export const RENTALITY_USER_SERVICE_ADDRESS = "${addresses.userProfileQuery}"
`

  fs.writeFileSync(generatedAddressesPath, content)
  console.log(`Updated Base Sepolia generated addresses: ${generatedAddressesPath}`)
}

function main() {
  if (!featureName) {
    console.log('FEATURE_NAME is not set; reading default Base Sepolia address book')
  }
  if (!fs.existsSync(indexerRoot)) {
    throw new Error(`Indexer root was not found: ${indexerRoot}`)
  }

  const addresses = {
    notificationService: readAddress('RentalityNotificationService'),
    carGatewayRead: readAddress('CarGatewayFacet2'),
    tripQuery: readAddress('TripQuery'),
    userProfileQuery: readAddress('UserProfileQuery'),
  }

  writeSubgraphYaml(addresses.notificationService)
  writeGeneratedAddresses(addresses)
  console.log(`Base Sepolia indexer config synced with startBlock=${startBlock}`)
}

main()
